tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true

build:
    dependencies:
        before:
            - sudo apt-get -y install php5-apcu
filter:
    excluded_paths: [build/*, tools/*, tests/*, public/*]
