language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

services:
  - redis-server

cache:
  directories:
  - vendor

before_script:
  - PHP=$TRAVIS_PHP_VERSION
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - sh -c "if [ $PHP != 'hhvm' ] && [ `php-config --vernum` -lt 70000 ] ; then echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi"
  - sh -c "if [ $PHP != 'hhvm' ] && [ `php-config --vernum` -ge 50400 ] && [ `php-config --vernum` -lt 70000 ]; then printf "yes\n" | pecl install -f apcu-4.0.10 ; fi"
  - sh -c "if [ $PHP != 'hhvm' ] && [ `php-config --vernum` -ge 70000 ] ; then printf "yes\n" | pecl install -f apcu-5.1.3 ; fi"
  - sh -c "if [ $PHP != 'hhvm' ] ; then phpenv config-add ./tests/apc.ini; fi"
  - if [ $PHP == '5.4' ] ; then ./set_guzzle5.sh; fi
  - composer global require hirak/prestissimo
  - composer self-update
  - if [ $PHP == '5.4' ] ; then composer install -o --prefer-dist --prefer-lowest; fi
  - if [ $PHP != '5.4' ] ; then composer install -o --prefer-dist; fi

script:
  - ant phpcs-ci
  - phpunit --testsuite=unit
  - if [ $PHP == '7.0' ] ; then phpunit --testsuite=integration; fi
  - ant behat

after_success:
  - ./push-docs-to-gh-pages.sh

notifications:
  hipchat:
    rooms:
      secure: VD5RvUZYVg1aokw8OeMhNfDPc39o2r4Jjq8s6U2QvMXzoiopHpj6+VYX1AHbhxMpBGmsgKfzbYQ6XfubJUeHq+FMzW3YEekwcyqXKCfWi5tLCE7Epb0dCySatztVTkqlXzXaAM6NhzdFxG6kQPiA9OcSvRPZmSwjuX4eYXRokRw=
