language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "hhvm"

before_script:
  - echo "yes" | pecl install apcu
  - echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --prefer-dist -o

matrix:
  allow_failures:
    - php: hhvm
