language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "hhvm"

before_script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]  && [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install -f apcu ; echo 'extension="apcu.so\napc.enabled=1\napc.enable_cli=1"' > ./tests/apc.ini ; else echo 'extension="apcu.so\napc.enabled=1\napc.enable_cli=1"' > ./tests/apc.ini ;fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/apc.ini; fi"
  - composer self-update
  - composer install --prefer-dist -o

matrix:
  allow_failures:
    - php: hhvm
