language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "hhvm"

before_script:
  - sh -c "if [[ $TRAVIS_PHP_VERSION != 'hhvm' && `php-config --vernum` -ge 50500 ]] ; then yes | pecl install -f apcu ; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/apc.ini; fi"
  - composer self-update
  - composer install --prefer-dist -o

matrix:
  allow_failures:
    - php: hhvm
