language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "hhvm"

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
  - vendor

before_script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]  && [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install -f apcu ; else echo 'extension="apc.so"' >> ./tests/apc.ini ; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/apc.ini; fi"
  - if [ $(phpenv version-name) = '5.4' ]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; else PHPUNIT_FLAGS=""; fi
  - composer self-update
  - composer install --prefer-source -o

script:
  - ant phpcs-ci
  - phpunit $PHPUNIT_FLAGS
  - if [ $TRAVIS_PHP_VERSION != 'hhvm' ]  && [ $(phpenv version-name) = '5.4' ]; then ant apigen; fi

after_success:
  - ./push-docs-to-gh-pages.sh

env:
  global:
    # GH_TOKEN environment variable for pushing documentation:
    - secure: "i0TL7GsZ8TIZgr7WB5qXEs8fF5sSJHGagLXEsn4DSgxI52GatfjeEaSJuAbbWV/Tg0jYidNevdhCpe7LT3IWwa2cLVRpaV1TDoQ6K4wo8zzMzAw4AMB8DO2dBY3Mz+puRN55YAV3OpEF/RiiIc7zXLW/+5H9UCOXrcnnpg6PpxE="
